version: "3"

services:
  drupal:
    image: bitnami/drupal:latest
    ports:
      - 8080:80
    volumes:
      - drupal-modules:/var/www/html/modules
      - drupal-profiles:/var/www/html/profiles
      - drupal-sites:/var/www/html/sites
      - drupal-themes:/var/www/html/themes
    enviorment:
      - MYSQL_HOST=mariadb
      - MYSQL_USER=YAM428
      - MYSQL_PASSWORD=030119048
      - MYSQL_DATABASE=final
    depends_on:
      - mariadb
    restart: always

  mariadb:
    image: maradb:latest
    enviorment:
      - MYSQL_ROOT_PASSWORD=030119048
      - MYSQL_DATABASE=final
    volumes:
      - mariadb-data:/var/lib/mysql
    restart: always
